services:

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: public
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
